name: Deploy Admin Fuel App (Self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy App on Server
        run: |
          cd /data/development/Master-Data
          git pull origin main
          npm install
          chmod +x restart.sh
          ./restart.sh
        shell: bash

